// Unified icon mapping for react-icons
// This file provides icon components for easy access and consistency

import {
  FiActivity,
  FiAlertCircle,
  FiAward,
  FiBell,
  FiCalendar,
  FiCheck,
  FiCheckCircle,
  FiCheckSquare,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiClock,
  FiDollarSign,
  FiDownload,
  FiEye,
  FiFilter,
  FiGift,
  FiGlobe,
  FiGrid,
  FiHash,
  FiImage,
  FiInfo,
  FiList,
  FiLoader,
  FiMail,
  FiMessageSquare,
  FiPlus,
  FiSave,
  FiSettings,
  FiShield,
  FiStar,
  FiTarget,
  FiTrendingDown,
  FiTrendingUp,
  FiUpload,
  FiUser,
  FiUsers,
  FiX,
  FiArrowDownLeft,
  FiArrowDownRight,
  FiArrowRight,
  FiArrowUpRight,
  FiLayers,
  FiAlertTriangle,
} from "react-icons/fi";
import { IoWalletOutline } from "react-icons/io5";

// Re-export all icons as a unified map
export const Icons = {
  Activity: FiActivity,
  AlertCircle: FiAlertCircle,
  Award: FiAward,
  Bell: FiBell,
  Calendar: FiCalendar,
  Check: FiCheck,
  CheckCircle: FiCheckCircle,
  CheckCheck: FiCheckSquare,
  ChevronDown: FiChevronDown,
  ChevronLeft: FiChevronLeft,
  ChevronRight: FiChevronRight,
  Clock: FiClock,
  DollarSign: FiDollarSign,
  Download: FiDownload,
  Eye: FiEye,
  Filter: FiFilter,
  Gift: FiGift,
  Globe: FiGlobe,
  Grid: FiGrid,
  Hash: FiHash,
  Image: FiImage,
  ImageIcon: FiImage,
  Info: FiInfo,
  LayoutGrid: FiGrid,
  List: FiList,
  ListOrdered: FiList,
  LoaderPinwheel: FiLoader,
  Mail: FiMail,
  Medal: FiAward,
  MessageSquare: FiMessageSquare,
  Plus: FiPlus,
  Quote: FiMessageSquare,
  Save: FiSave,
  ScanEye: FiEye,
  Settings: FiSettings,
  Shield: FiShield,
  Star: FiStar,
  Target: FiTarget,
  TrendingDown: FiTrendingDown,
  TrendingUp: FiTrendingUp,
  Trophy: FiAward,
  Upload: FiUpload,
  User: FiUser,
  Users: FiUsers,
  Wallet: IoWalletOutline,
  X: FiX,
  ArrowDownLeft: FiArrowDownLeft,
  ArrowDownRight: FiArrowDownRight,
  ArrowRight: FiArrowRight,
  ArrowUpRight: FiArrowUpRight,
  Brain: FiLayers,
  Coins: FiDollarSign,
  ShieldAlert: FiAlertTriangle,
  Dice: FiAward,
  HelpCircle: FiInfo,
  CheckCircle2: FiCheckCircle,
};

export type IconName = keyof typeof Icons;
